<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CourierProject.Application\CourierProject.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"  />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"  />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql"  />
  </ItemGroup>

  <PropertyGroup>

  </PropertyGroup>

</Project>
